#! /bin/bash

#
# License: BSD 3-Clause License
# Copyright (C) 2018-2019, New York University , Max Planck Gesellschaft
# Copyright note valid unless otherwise stated in individual files.
# All rights reserved.
# 

roslaunch robot_properties_solo visual_rviz.launch
